import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Aside from '@/components/Aside'
import { PageProvider } from '@/context/PageContext'

const inter = Inter({ subsets: ['latin'] })

export const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageProvider>{children}</PageProvider>
      </body>
    </html>
  )
}
